### ISSUE TITLE
Can you please instruct how to export to onnx?

### ISSUE THREAD

**Issue by dbickson** [SysCV/MaskFreeVIS#3]
- What is the required normalization for images before model
- What is the necessary post processing (if any) once the model is scored?

Many thanks for a great project!

**Comment by lkeab** [comment]
Hi thanks for watching the project. we have the image processing code code [here](https://github.com/SysCV/MaskFreeVIS/blob/main/demo_video/demo.py#L117) and result post-processsing code [here](https://github.com/SysCV/MaskFreeVIS/blob/main/demo_video/predictor.py#L46).

**Comment by lkeab** [comment]
for exporting to onnx, since we implement based on detectron2, please refer to the discussion [here](https://github.com/facebookresearch/detectron2/issues/4414)
