### ISSUE TITLE
Bounding boxes requirement during training?

### ISSUE THREAD

**Issue by zshn25** [SysCV/MaskFreeVIS#8]
Great work guys, I was wondering if you require bounding box labels during training? There’s a brief mention of this in the video and also in the paper. Just wanted to make sure.

**Comment by lkeab** [comment]
Yes, it requires bounding boxes. "In this work, we aim to remove the mask-annotation requirement. We propose MaskFreeVIS, achieving highly competitive VIS performance, while only using cheap bounding box annotations for the object state."
